"""widen password_hash to fit scrypt hashes

Revision ID: 452053708837
Revises: 3edbacb4f012
Create Date: 2026-08-11 00:45:39.076934

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '452053708837'
down_revision = '3edbacb4f012'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('password_hash',
               existing_type=sa.VARCHAR(length=128),
               type_=sa.String(length=255),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('password_hash',
               existing_type=sa.String(length=255),
               type_=sa.VARCHAR(length=128),
               existing_nullable=False)

    # ### end Alembic commands ###
